version: '3.9'
services:
  app:
    build: .
    container_name: laravel
    volumes:
      - '.:/var/www'
    depends_on:
      - mysql
    networks:
      - laravel
  nginx:
    image: 'nginx:alpine'
    container_name: laravel_nginx
    ports:
      - '8080:80'
    volumes:
      - '.:/var/www'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - app
    networks:
      - laravel
  mysql:
    image: 'mysql:8.0'
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - 'db_data:/var/lib/mysql'
    ports:
      - '3306:3306'
    networks:
      - laravel
volumes:
  db_data: null
networks:
  laravel: null
